### ISSUE TITLE
Add error handling to the `page_scraper` process

### ISSUE THREAD

**Issue by akellehe** [akellehe/fb_calendar#17]
The `page_scraper` process keeps all our events up-to-date by scraping them continuously from Facebook and updating our database entries.

At the moment it's pretty bare bones. Add error handling (`try`/`except` blocks) to the `continuously_update` and `priority_update` methods so we catch _all_ exceptions and log them with the appropriate log level.

**Comment by ak9999** [comment]
Done in #28.
