### ISSUE TITLE
Ansible is doing a bad job of restarting processes

### ISSUE THREAD

**Issue by akellehe** [akellehe/fb_calendar#18]
It seems that not every time we do an ansible deploy the services are restarted. We should investigate this.

**Comment by akellehe** [comment]
I think this might be related to the ansible scripts running the database role ahead of the page scraper role.

**Comment by ak9999** [comment]
Closing for now as referenced in this [comment](https://github.com/akellehe/fb_calendar/issues/22#issuecomment-279240979).
