### ISSUE TITLE
Remove references to `gnupg`

### ISSUE THREAD

**Issue by akellehe** [akellehe/fb_calendar#2]
As I was working toward a simple method for sharing application secrets I took down the path of implementing gpg for pgp encryption. 

This proved to be pretty complicated since during a deploy we don't have access to any `tty` without jumping through some hoops...and accessing secret gpg keys was non-trivial. 

Ansible vault is a standard, accepted approach to managing application secrets, so I made the decision to fall back to that as the gpg approach was taking a long time.

Now there are vestiges of that approach left in the code base.

- [x] Remove the `.gnupg` directory in the deploy scripts
- [x] Don't install `gpg` or `gpg-agent` in the deploy scripts
- [x] Remove the `.gnupg` home directory in the application root
- [x] Remove the associated entries in `.gitignore`

**Comment by ak9999** [comment]
So far:
- [ ] Remove the `.gnupg` directory in the deploy scripts
- [ ] Don't install `gpg` or `gpg-agent` in the deploy scripts
- [x] Remove the `.gnupg` home directory in the application root
- [x] Remove the associated entries in `.gitignore`

Still looking through the deploy scripts.

**Comment by akellehe** [comment]
@ak9999 i _think_ you can actually check the boxes _in_ the issue above.

**Comment by ak9999** [comment]
Done. I _think_.

**Comment by akellehe** [comment]
Nice, Abdullah. You should check out the procedure page now... I think the next step is rebasing or something, then submitting a pull request. Generally speaking, though, there's no harm in starting a pull request early and labeling it `wip`. It gives teammates a chance to jump in and point out pitfalls and prior art.
