### ISSUE TITLE
page_scraper is installed before database

### ISSUE THREAD

**Issue by akellehe** [akellehe/fb_calendar#22]
For some reason the `page_scraper` role is run by ansible before the `fb_calendar_db` role. This causes the `page_scraper` to attempt to connect to the database before it's available resulting in an exception causing the process to hang indefinitely.

We just need to enforce the order of the roles in ansible.

**Comment by akellehe** [comment]
I think this might be the cause of https://github.com/akellehe/fb_calendar/issues/18

**Comment by ak9999** [comment]
For now we'll close this and re-visit it if it comes up again.
