### ISSUE TITLE
Move to Python 3?

### ISSUE THREAD

**Issue by ak9999** [akellehe/fb_calendar#58]
Currently the project runs on Python 2.7, but Python 2.7 will not be maintained past 2020. We should start thinking about migrating to 3.6 before the project gets too big.

**Comment by pisoiasul** [comment]
I'd say no for the moment

**Comment by akellehe** [comment]
Let's seriously consider this when we get the MVP out the door

**Comment by akellehe** [comment]
Closing for now.
