### ISSUE TITLE
dev-requirements.txt not being installed by scripts/test

### ISSUE THREAD

**Issue by akellehe** [akellehe/fb_calendar#8]
For some reason when we change dev-requirements.txt pip attempts to build those requirements in the working directory instead of the virtualenv (even when we use the virtualenv pip). 

The expected behavior is for pip to pick up changes in dev-requirements.txt (in the `scripts/test` script) and install those packages in the `fb_calendar` virtual environment. 

This card is to investigate and resolve the issue such that all we have to do to get the latest `dev-requirements.txt` installed is to run `scripts/test`

**Comment by ak9999** [comment]
In my testing everything gets installed to the virtual environment as it should. Closing for now but will revisit it if it comes up again.
