### ISSUE TITLE
Add some options to the user events handler to return various "channels"

### ISSUE THREAD

**Issue by pisoiasul** [akellehe/fb_calendar#91]
Add a new string parameter "types" to the /events?fbid=xyz handler (handlers.UserEvents);

ff types=0 -> it should return the events in the "Wake and Shake" mode (see #53), i.e. it should ignore the fbid and instead return events from FEED_USER
if types=1 -> it should return the events in the "Find a Party" mode (see #53), i.e. events for the fbid user
if types=0,1 -> it should get both feeds, merge them and return them. Be careful for removing duplicates

**Comment by akellehe** [comment]
This is not necessary, @pisoiasul the configuration options handle this already (See issue 53)

**Comment by pisoiasul** [comment]
It is, remember we've discussed we're not doing 2 apps anymore, but only one app. And in Settings we'll have a tick mark "Show events from pages you like" or something like that. That settings will mean "types=0,1" (by default types=0)

**Comment by akellehe** [comment]
But we're launching as just "wake and shake", not "find a party"

**Comment by pisoiasul** [comment]
:))

But we decided to have an option to also show your own personal events.
We discussed this 2 weeks ago.

**Comment by akellehe** [comment]
Maybe we're conflating "personal events" with the user feed. we shouldn't be showing party events yet.. .we should have a feed that shows what a user has swiped right on, though
